### ISSUE TITLE
Is the location of the project templates configurable?

### ISSUE THREAD

**Issue by eclifford** [gruntjs/grunt-init#10]
I've read through the documentation/source and I know by default it looks in the tasks/init dir as well as the users /.grunt/tasks/init dir for tasks.

What I'm trying to do is build a deployable solution with some prepackaged templates to choose from. How would I go about doing this without modifying grunt source?

Thank you

**Comment by monolithed** [comment]
> The grunt-init task will eventually be deprecated and the functionality will be subsumed by Yeoman. This is basically to eliminate duplication of effort between the projects. Yeoman is upstreaming a bunch of their tasks into grunt-contrib and we're giving them grunt-init to use as a base for their rewrite.
> In the long term, Yeoman will be a scaffolding tool only and grunt will be a task runner only. I'm not too clear on the best solution for you in the short term.

In this case, the package must be marked as deprecated
