### ISSUE TITLE
Question: Is there a sample of using glob replace in rename.json?

### ISSUE THREAD

**Issue by richard-edwards** [gruntjs/grunt-init#57]
I'm trying to create a rename.json file that will do a search/replace on multiple files at once using the glob matching. Is this possible?

For example:

Files in template could be Test1.js, Test2.js, ..., Test9.js. I'd like to replace Test with a prompt in each one. So if my prompt was named 'Company', I would like to rename files Company1.js, Company2.js, ..., Company9.js using a single rename.json entry such as this:

{
  "Test_.js" : "{%= Company %}_.js"
}

instead of putting a single entry for each of the 9 files.

**Comment by MickeyKay** [comment]
+1 Any leads yet?
